server:
  port: 8082

#-id
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: messages_get
          uri: lb://messagesServer
          predicates:
            - Path=/messages/test
            - Method=GET
        - id: account_get
          uri: lb://accountServer
          predicates:
            - Path=/account/test
            - Method=GET
        - id: post_get
          uri: lb://postServer
          predicates:
            - Path=/post/test
            - Method=GET
        - id: search_get
          uri: lb://searchServer
          predicates:
            - Path=/search/test
            - Method=GET



eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

