server:
  port: 8082

#-id
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: messages
          uri: lb://messagesServer
          predicates:
            - Path=/user/dialog/**, /chat, /app/chat, /chat/**
        - id: account
          uri: lb://accountServer
          predicates:
            - Path=/user/**,/registration,/input,/account/**
        - id: post
          uri: lb://postServer
          predicates:
            - Path=/post/**
        - id: search
          uri: lb://searchServer
          predicates:
            - Path=/search, /search/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

