server:
  port: 0

#-id
spring:
  application:
    name: postServer


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
