server:
  port: 0

spring:
  application:
    name: accountServer
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/social_network
    username: postgres
    password: "112348Diman"
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml
  enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

